name: gameplay-highlights
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pyyaml
  - pillow
  - tqdm
  - rich
  - scipy

  - pip:
      - opencv-python
      - moviepy
      - pydub
      - torch
      - torchaudio
      - TTS
